# -*- coding: utf-8 -*-
"""
/***************************************************************************
 SeisPlotPy
                                 A QGIS plugin
 SEG-Y Visualization and Navigation
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-11-26
        copyright            : (C) 2025 by Arjun V H
        email                : arjunvelliyidathu@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

# -*- coding: utf-8 -*-
def classFactory(iface):
    """
    Load SeisPlotPy class, but only if dependencies are available.
    """
    from .dependencies import check_dependencies

    # 1. Check dependencies
    if not check_dependencies(iface):
        # Return a dummy plugin so QGIS doesn't error, but it will do nothing.
        class DummyPlugin:
            def __init__(self, iface):
                pass

            def initGui(self):
                pass

            def unload(self):
                pass

        return DummyPlugin(iface)

    # 2. Dependencies are OK - load the real plugin
    from .seisplotpy import SeisPlotPy
    return SeisPlotPy(iface)
