# -*- coding: utf-8 -*-
"""
/***************************************************************************
 SeisPlotPy
                                 A QGIS plugin
 SEG-Y Visualization and Navigation
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-11-26
        copyright            : (C) 2025 by Arjun V H
        email                : arjunvelliyidathu@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

# -*- coding: utf-8 -*-
def classFactory(iface):  # pylint: disable=invalid-name
    """
    Load SeisPlotPy class. 
    Checks dependencies first.
    """
    # 1. Import dependency checker
    from .dependencies import install_dependencies
    
    # 2. Run the check
    # If it returns False (installed just now, or user said No), do not load the plugin
    if not install_dependencies(iface):
        # Return a dummy class to prevent QGIS error, but plugin won't work yet
        class DummyPlugin:
            def __init__(self, iface): pass
            def initGui(self): pass
            def unload(self): pass
        return DummyPlugin(iface)

    # 3. If True, dependencies exist. Load normally.
    from .seisplotpy import SeisPlotPy
    return SeisPlotPy(iface)