# -*- coding: utf-8 -*-
"""
/***************************************************************************
 SeisPlotPy
                                 A QGIS plugin
 SEG-Y Visualization and Navigation
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-11-26
        git sha              : $Format:%H$
        copyright            : (C) 2025 by Arjun V H
        email                : arjunvelliyidathu@gmail.com
 ***************************************************************************/

/***************************************************************************
 * *
 * This program is free software; you can redistribute it and/or modify  *
 * it under the terms of the GNU General Public License as published by  *
 * the Free Software Foundation; either version 2 of the License, or     *
 * (at your option) any later version.                                   *
 * *
 ***************************************************************************/
"""
import os
import json
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction, QMessageBox
from .resources import *

# Import the custom tool
from .core.map_tool import SeismicNavigationTool

class SeisPlotPy:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor."""
        self.iface = iface
        self.plugin_dir = os.path.dirname(__file__)
        
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'SeisPlotPy_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        self.actions = []
        self.menu = self.tr(u'&SeisPlotPy')

        self.controllers = [] 
        self.first_start = None
        self.tool = None

    def tr(self, message):
        return QCoreApplication.translate('SeisPlotPy', message)

    def add_action(self, icon_path, text, callback, enabled_flag=True, add_to_menu=True, add_to_toolbar=True, status_tip=None, whats_this=None, parent=None):
        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)
        if status_tip is not None:
            action.setStatusTip(status_tip)
        if whats_this is not None:
            action.setWhatsThis(whats_this)
        if add_to_toolbar:
            self.iface.addToolBarIcon(action)
        if add_to_menu:
            self.iface.addPluginToMenu(self.menu, action)
        self.actions.append(action)
        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""
        
        # 1. Load Button
        icon_path = ':/plugins/seisplotpy/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u'Load SEG-Y'),
            callback=self.run,
            parent=self.iface.mainWindow())
            
        # 2. Link Cursor Button
        self.action_link = self.add_action(
            icon_path, 
            text=self.tr(u'Link/Nav Tool'),
            callback=self.activate_tool,
            parent=self.iface.mainWindow(),
            status_tip="Activate to link QGIS cursor with Seismic View"
        )
        self.action_link.setCheckable(True)

        # 3. Initialize the tool
        self.tool = SeismicNavigationTool(self.iface.mapCanvas())
        
        # 4. Connect Tool Signals
        self.tool.canvas_moved.connect(self.broadcast_hover)
        self.tool.canvas_double_clicked.connect(self.broadcast_click)
        
        # 5. About action (menu only, no toolbar icon)
        self.about_action = self.add_action(
            icon_path,
            text=self.tr(u'About SeisPlotPy'),
            callback=self.show_about_dialog,
            parent=self.iface.mainWindow(),
            add_to_toolbar=False
        )
        
        # 6. Connect Project Persistence Signals
        from qgis.core import QgsProject
        QgsProject.instance().writeProject.connect(self.writeProject)
        QgsProject.instance().readProject.connect(self.readProject)

        self.first_start = True

    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        if self.tool and self.iface.mapCanvas().mapTool() == self.tool:
            self.iface.mapCanvas().unsetMapTool(self.tool)
            
        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&SeisPlotPy'),
                action)
            self.iface.removeToolBarIcon(action)

    def run(self):
        """Launch a new Controller (Window)"""
        from .controller import MainController
        new_controller = MainController(self.iface)
        self.controllers.append(new_controller)

    def activate_tool(self):
        """Sets our custom tool on the canvas."""
        if self.action_link.isChecked():
            self.iface.mapCanvas().setMapTool(self.tool)
        else:
            self.iface.mapCanvas().unsetMapTool(self.tool)
    
    def show_about_dialog(self):
        """Show a simple About dialog with author and support info."""
        text = (
            "SeisPlotPy is currently being developed and maintained by Arjun V H\n"
            "Contact: arjunvelliyidathu@gmail.com\n\n"
            "SeisPlotPy is released under the GPL-2.0 license.\n\n"
            "Found a bug? Need a feature?\n"
            "Please report it here:\n"
            "https://github.com/arjun-vh/SeisPlotPy-QGIS/issues"
        )

        QMessageBox.information(
            self.iface.mainWindow(),
            "About SeisPlotPy",
            text
        )

    def broadcast_hover(self, point):
        """Send mouse coordinates to ALL windows (even hidden ones)."""
        for ctrl in self.controllers:
            # Only send hover events to visible windows to save performance
            if ctrl.view.isVisible() and hasattr(ctrl, 'handle_map_hover'):
                ctrl.handle_map_hover(point)

    def writeProject(self, doc):
        """Called when QGIS saves the project. Saves navigation layers logic."""
        # We need to save the MEMORY layers because QGIS doesn't save them.
        # We find them by looking for our custom property.
        
        root = doc.documentElement()
        plugin_node = doc.createElement("SeisPlotPy")
        
        from qgis.core import QgsProject
        layers = QgsProject.instance().mapLayers().values()
        
        for layer in layers:
            # Check if this is one of our layers
            path = layer.customProperty("seisplotpy_path")
            if not path: continue
            
            state_json = layer.customProperty("seisplotpy_state")
            # --- FIX: Save Dual Paths ---
            path_rel = layer.customProperty("seisplotpy_path_relative")
            path_abs = layer.customProperty("seisplotpy_path_absolute")
            # ----------------------------
            
            # Create Node
            layer_node = doc.createElement("NavLayer")
            layer_node.setAttribute("path", str(path))
            if path_rel: layer_node.setAttribute("path_relative", str(path_rel))
            if path_abs: layer_node.setAttribute("path_absolute", str(path_abs))
            
            if state_json:
                layer_node.setAttribute("state", str(state_json))
            
            # Save Geometry Params (Critical for custom headers)
            geom_params = layer.customProperty("seisplotpy_geometry_params")
            if geom_params:
                layer_node.setAttribute("geometry_params", str(geom_params))
            
            # Save CRS - Critical for memory layers
            if layer.crs().isValid():
                layer_node.setAttribute("crs", layer.crs().authid())

            # Serialize Geometry (The Red Line)
            try:
                # We expect 1 feature
                for feat in layer.getFeatures():
                    geom = feat.geometry()
                    wkt = geom.asWkt()
                    layer_node.setAttribute("wkt", wkt)
                    break 
            except Exception as e:
                print(f"SeisPlotPy Warning [Layer Geometry Save]: {e}")
            
            plugin_node.appendChild(layer_node)
            
        root.appendChild(plugin_node)

    def readProject(self, doc):
        """Called when QGIS opens a project. Restores custom properties and CRS."""
        root = doc.documentElement()
        plugin_node = root.firstChildElement("SeisPlotPy")
        if plugin_node.isNull(): return
        
        from qgis.core import QgsProject, QgsCoordinateReferenceSystem, QgsFeature, QgsGeometry
        
        # Build a map of saved layer info
        saved_layers = {}
        layer_node = plugin_node.firstChildElement("NavLayer")
        while not layer_node.isNull():
            path = layer_node.attribute("path")
            state = layer_node.attribute("state")
            wkt = layer_node.attribute("wkt")
            crs_id = layer_node.attribute("crs")
            geom_params = layer_node.attribute("geometry_params")
            
            # --- FIX: Read Dual Paths ---
            path_rel = layer_node.attribute("path_relative")
            path_abs = layer_node.attribute("path_absolute")
            # ----------------------------
            
            if path:
                # Use absolute path name if available for robust matching, or just basename
                # The layer name in QGIS is typically os.path.basename(path)
                layer_name = os.path.basename(path)
                saved_layers[layer_name] = {
                    "path": path, 
                    "path_rel": path_rel,
                    "path_abs": path_abs,
                    "state": state, 
                    "wkt": wkt,
                    "crs": crs_id,
                    "geometry_params": geom_params
                }
            
            layer_node = layer_node.nextSiblingElement("NavLayer")
        
        # QGIS 3.x auto-restores memory layers, but often loses CRS and Custom Props.
        # We find them by name and patch them up.
        current_layers = list(QgsProject.instance().mapLayers().values())
        
        for layer in current_layers:
            layer_name = layer.name()
            if layer_name in saved_layers:
                info = saved_layers[layer_name]
                
                # 1. Restore Metadata (Link to Plugin)
                layer.setCustomProperty("seisplotpy_path", info["path"])
                # --- FIX: Restore Dual Paths ---
                if info["path_rel"]: layer.setCustomProperty("seisplotpy_path_relative", info["path_rel"])
                if info["path_abs"]: layer.setCustomProperty("seisplotpy_path_absolute", info["path_abs"])
                # -------------------------------
                
                if info["state"]:
                    layer.setCustomProperty("seisplotpy_state", info["state"])
                if info["geometry_params"]:
                    layer.setCustomProperty("seisplotpy_geometry_params", info["geometry_params"])
                
                # 2. Fix CRS (Crucial: Memory layers default to 4326 on load)
                if info["crs"]:
                     crs = QgsCoordinateReferenceSystem(info["crs"])
                     if crs.isValid() and layer.crs() != crs:
                         layer.setCrs(crs)
                
                # 3. Restore Geometry (CRITICAL: QGIS restores layer shell but wipes features)
                if layer.featureCount() == 0 and info["wkt"]:
                    try:
                        pr = layer.dataProvider()
                        feat = QgsFeature()
                        feat.setGeometry(QgsGeometry.fromWkt(info["wkt"]))
                        
                        # Attributes: [filename, traces] - we assume 0 traces for now as data isn't loaded
                        feat.setAttributes([layer_name, 0])
                        
                        pr.addFeatures([feat])
                        layer.updateExtents()
                    except Exception as e:
                        # Log error if geometry restoration fails
                        print(f"SeisPlotPy: Failed to restore geometry for {layer_name}: {e}")
                
                 # Trigger re-render extent
                if self.iface.mapCanvas():
                     layer.updateExtents()
                     self.iface.mapCanvas().refresh()

    def broadcast_click(self, point):
        """Handle double-click: Open window if clicking a known layer."""
        
        # ... (keep existing lines for propagating to controllers) ...
        for ctrl in self.controllers:
            if hasattr(ctrl, 'handle_map_click'):
                ctrl.handle_map_click(point)
                
        # 2. Check for Navigation Layer hits
        from qgis.core import QgsProject, QgsGeometry, QgsFeatureRequest, QgsMapLayer, QgsCoordinateTransform
        
        layers = self.iface.mapCanvas().layers() 
        map_crs = self.iface.mapCanvas().mapSettings().destinationCrs()
        tol = self.iface.mapCanvas().mapUnitsPerPixel() * 5

        for layer in layers:
            if layer.type() != QgsMapLayer.VectorLayer: continue
            
            # --- FIX STARTS HERE ---
            # 1. Get the stored path string (could be "./Data/line.sgy" OR "E:/Data/line.sgy")
            raw_path = layer.customProperty("seisplotpy_path")
            if not raw_path: continue
            
            # 2. Try to resolve it as a relative path first (Standard QGIS behavior)
            # If raw_path is absolute, readPath() usually just returns it as is.
            # If raw_path is relative, it joins it with the project folder.
            resolved_path = QgsProject.instance().readPath(raw_path)
            
            # 3. VERIFY & FAIL-SAFE
            final_path_to_open = None
            
            if os.path.exists(resolved_path):
                # Scenario A: The relative path worked (Best case)
                final_path_to_open = resolved_path
            elif os.path.exists(raw_path):
                # Scenario B: The relative path failed, but the raw string works as an absolute path
                # (This catches old projects or projects saved with absolute paths)
                final_path_to_open = raw_path
            
            # If neither worked, we can't open the file. Skip this layer.
            if final_path_to_open is None:
                print(f"SeisPlotPy: Could not locate file. Tried '{resolved_path}' and '{raw_path}'")
                continue

            # ... (Rest of the CRS transformation logic remains the same) ...
            search_rect_map = QgsGeometry.fromPointXY(point).buffer(tol, 5).boundingBox()
            
            if layer.crs() != map_crs:
                try:
                    xform = QgsCoordinateTransform(map_crs, layer.crs(), QgsProject.instance())
                    search_rect_layer = xform.transformBoundingBox(search_rect_map)
                except Exception: continue
            else:
                search_rect_layer = search_rect_map
            
            request = QgsFeatureRequest().setFilterRect(search_rect_layer)
            iterator = layer.getFeatures(request)
            has_feature = False
            for feat in iterator:
                has_feature = True
                break 
            
            if has_feature:
                # Pass the RESOLVED (Absolute) path to the opener
                self.open_layer_window(layer, final_path_to_open)
                return

    def open_layer_window(self, layer, path):
        # Check if already open
        for ctrl in self.controllers:
            if ctrl.data_manager and ctrl.data_manager.file_path == path:
                ctrl.view.showNormal()
                ctrl.view.activateWindow()
                ctrl.view.raise_()
                return

        # Open New
        from .controller import MainController
        try:
            state_json = layer.customProperty("seisplotpy_state")
            state = json.loads(state_json) if state_json else None
            
            new_controller = MainController(self.iface)
            
            # Link to existing layer
            new_controller.qgis_layer = layer
            layer.willBeDeleted.connect(new_controller.on_layer_deleted) 
            
            # Initialize with file (metadata only, no new layer creation)
            new_controller.load_file_from_path(path, load_data_only=True)
            
            if state:
                new_controller.restore_state(state)
            else:
                # Fallback: If no state exists (old save), force a restore
                new_controller.restore_state({"file_path": path})

            self.controllers.append(new_controller)
            
            # Show the window explicitly
            new_controller.view.showNormal()
            new_controller.view.activateWindow()
            new_controller.view.raise_()
                
        except Exception as e:
            import traceback
            traceback.print_exc()
            QMessageBox.critical(self.iface.mainWindow(), "Error", f"Failed to open line: {e}")